baseURL: https://suse-projects.github.io
languageCode: en-us
title: SUSE Is Open Source
disableKinds:
- taxonomy
- term
markup.goldmark.renderer:
  hardWraps: true
params:
  featuredLimit: 3
  featured:
  - Rancher
  - K3S
  - Longhorn
  - Harvester
  - Kubewarden
  - K3OS
  - SLE BCI
  categoryMap:
    ai-ml: AI/ML
