baseURL: https://suse-projects.github.io
languageCode: en-us
title: SUSE On GitHub
disableKinds:
- taxonomy
- term
markup.goldmark.renderer:
  hardWraps: true
params:
  featuredLimit: 6
  featured:
  - Rancher
  - K3S
  - Longhorn
  - Harvester
  - RKE
  - RKE Government
  categoryMap:
    ai-ml: AI/ML
